spring.config.import=classpath:database.properties

spring.application.name=myfancypdf.springboot
cdn.url=https://dev-cdn.agmiar.com.uy

# H2 support
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.url=jdbc:h2:~/mySpringBootH2Database
#spring.datasource.username=sa
#spring.datasource.password=sa

# Postgres support
spring.datasource.driver-class-name=${JDBC_DRIVER}
spring.datasource.url=jdbc:postgresql://${JDBC_HOST}:${JDBC_PORT}/${JDBC_DATABASE}?currentSchema=${JDBC_SCHEMA}
spring.datasource.username=${JDBC_USERNAME}
spring.datasource.password=${JDBC_PASSWORD}

## Forzar la ejecución de schema.sql
#spring.sql.init.mode=always
#spring.sql.init.schema-locations=classpath:schema.sql

logging.level.org.springframework.jdbc.core.JdbcTemplate = DEBUG